#!/usr/bin/env bash
set -euo pipefail

# Generates a canonical/sbomber manifest for artifacts that were just built in
# this workflow run, so they can be scanned before anything is published.
#
# This is the pre-publish counterpart to the Trivy job: it consumes the same
# packed-rock / packed-snap GitHub artifacts, but submits them to Canonical's
# internal SBOM and security scanning services instead of scanning locally.
# Every artifact is referenced as a local `source`, so nothing is downloaded
# from the Snap Store or GHCR.
#
# Required environment:
#   ARTIFACTS        JSON list of {name, path} objects, as produced by
#                    rocks-discover.yaml / snaps-discover.yaml.
#   ARTIFACT_KIND    "rock" or "snap".
#   PKG_DIR          Directory holding the downloaded packed files.
#   SBOM_DEPARTMENT  Department to attribute the SBOM request to.
#   SBOM_TEAM        Team to attribute the SBOM request to.
#   SBOM_EMAIL       Address notified when a report is ready.
#
# Optional environment:
#   PLATFORMS        Space-separated architectures. Default: "amd64 arm64".
#   OUTPUT           Manifest path to write. Default: sbom_manifest.yaml.
#   RELEASE_CHANNEL  SSDLC release channel (risk only). Default: edge.
#   REPORT_SSDLC     "true" to also push secscan results to the long-term
#                    SSDLC scan registry. Default: false, because pull request
#                    builds are never released and must not be registered.

: "${ARTIFACTS:?ARTIFACTS must be set to a JSON list of {name, path}}"
: "${ARTIFACT_KIND:?ARTIFACT_KIND must be set to rock or snap}"
: "${PKG_DIR:?PKG_DIR must be set}"
: "${SBOM_DEPARTMENT:?SBOM_DEPARTMENT must be set}"
: "${SBOM_TEAM:?SBOM_TEAM must be set}"
: "${SBOM_EMAIL:?SBOM_EMAIL must be set}"

PLATFORMS="${PLATFORMS:-amd64 arm64}"
OUTPUT="${OUTPUT:-sbom_manifest.yaml}"
RELEASE_CHANNEL="${RELEASE_CHANNEL:-edge}"
REPORT_SSDLC="${REPORT_SSDLC:-false}"

case "${ARTIFACT_KIND}" in
  rock) craft_relpath="rockcraft.yaml" ;;
  snap) craft_relpath="snap/snapcraft.yaml" ;;
  *)
    echo "ARTIFACT_KIND must be 'rock' or 'snap', got '${ARTIFACT_KIND}'" >&2
    exit 1
    ;;
esac

# Resolve the Ubuntu release an artifact is built on, for the SSDLC cycle.
# Rocks use "ubuntu@26.04" (or "bare", in which case build-base decides);
# snaps use "core26".
resolve_cycle() {
  local craft_file="$1" base

  base=$(yq -r '.base' "${craft_file}")

  case "${base}" in
    bare)
      base=$(yq -r '.build-base' "${craft_file}")
      echo "${base##*@}"
      ;;
    core*)
      # "core26" -> "26.04". Snap bases only ever track LTS releases.
      echo "${base#core}.04"
      ;;
    *)
      # "ubuntu@26.04" -> "26.04"
      echo "${base##*@}"
      ;;
  esac
}

{
  echo "# Generated by .github/scripts/generate-sbom-manifest.sh. Do not edit."
  echo "clients:"
  echo "  sbom:"
  echo "    department: ${SBOM_DEPARTMENT}"
  echo "    team: ${SBOM_TEAM}"
  echo "    email: ${SBOM_EMAIL}"
  echo "  secscan: {}"
  echo
  echo "artifacts:"
} >"${OUTPUT}"

found=0
while read -r name path; do
  craft_file="${path}/${craft_relpath}"
  if [[ ! -f "${craft_file}" ]]; then
    echo "No ${craft_relpath} found at ${path}" >&2
    exit 1
  fi

  version=$(yq -r '.version' "${craft_file}")
  cycle=$(resolve_cycle "${craft_file}")

  for platform in ${PLATFORMS}; do
    # rockcraft and snapcraft both emit <name>_<version>_<arch>.<ext>.
    file=$(find "${PKG_DIR}" -type f \
      -name "${name}_*_${platform}.${ARTIFACT_KIND}" | sort | head -n1)

    if [[ -z "${file}" ]]; then
      echo "No ${name}_*_${platform}.${ARTIFACT_KIND} found in ${PKG_DIR}" >&2
      echo "Available files:" >&2
      find "${PKG_DIR}" -type f >&2
      exit 1
    fi

    {
      # sbomber cannot detect a rock's version at all, and would misparse a
      # locally built snap's filename as its revision, so always be explicit.
      echo "  - name: ${name}-${platform}"
      echo "    type: ${ARTIFACT_KIND}"
      echo "    source: $(realpath "${file}")"
      echo "    version: \"${version}\""

      if [[ "${REPORT_SSDLC}" == "true" ]]; then
        echo "    ssdlc_params:"
        echo "      name: ${name}"
        echo "      version: \"${version}\""
        echo "      channel: ${RELEASE_CHANNEL}"
        echo "      cycle: \"${cycle}\""
      fi
    } >>"${OUTPUT}"

    found=$((found + 1))
  done
done < <(jq -r '.[] | "\(.name) \(.path)"' <<<"${ARTIFACTS}")

if [[ "${found}" -eq 0 ]]; then
  echo "No artifacts matched; refusing to submit an empty manifest" >&2
  exit 1
fi

echo "Wrote ${OUTPUT} with ${found} artifact(s):"
cat "${OUTPUT}"
