# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
name: Rock lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  yaml-lint:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint on snaps
        run: yamllint --no-warnings ./valkey/snaps/

      - name: Run yamllint on rocks
        run: yamllint --no-warnings ./valkey/rocks/
